CREATE TABLE page_view (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    page VARCHAR(20) NOT NULL,
    gym_id BIGINT REFERENCES gym(id),
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE page_view ENABLE ROW LEVEL SECURITY;
