CREATE TABLE gym (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    max_users INTEGER NOT NULL,
    google_login_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_gym_slug UNIQUE (slug),
    CONSTRAINT ck_gym_max_users CHECK (max_users > 0)
);

CREATE TABLE gym_block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL,
    label VARCHAR(150) NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    capacity INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_gym_block_gym FOREIGN KEY (gym_id) REFERENCES gym (id) ON DELETE CASCADE,
    CONSTRAINT ck_gym_block_capacity CHECK (capacity > 0),
    CONSTRAINT ck_gym_block_time CHECK (start_time < end_time)
);

CREATE INDEX idx_gym_block_gym_id ON gym_block (gym_id);
