-- Lista de espera por clase: cuando un bloque está lleno, un socio puede pedir que le avisen
-- si se libera un cupo (ver WaitlistService). notified_at queda null hasta que le toca su
-- turno de aviso (cabeza de la lista con ventaja, o el resto cuando esa ventana vence sin que
-- nadie reserve) — mientras esté null, sigue "esperando su turno" para ser notificado.
CREATE TABLE class_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_block_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    class_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    notified_at TIMESTAMP,
    CONSTRAINT fk_class_waitlist_block FOREIGN KEY (gym_block_id) REFERENCES gym_block (id) ON DELETE CASCADE,
    CONSTRAINT fk_class_waitlist_member FOREIGN KEY (member_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_class_waitlist_slot UNIQUE (gym_block_id, member_id, class_date)
);

CREATE INDEX idx_class_waitlist_occurrence ON class_waitlist (gym_block_id, class_date);
CREATE INDEX idx_class_waitlist_member_id ON class_waitlist (member_id);

ALTER TABLE class_waitlist ENABLE ROW LEVEL SECURITY;
