-- "Memoria Viva": bitácora cíclica de rutinas — el profesor define una pauta de N días simples
-- (solo título, sin ejercicios prescritos), el socio anota qué hizo cada vez que asiste (reserva
-- con check-in real, nunca una reserva suelta). Ver diseño completo + gaps cerrados en la memoria
-- de proyecto mygym_memoria_viva_design (sesión 2026-09-30 / 2026-10-02).

CREATE TABLE workout_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_workout_plan_member FOREIGN KEY (member_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- Un solo plan activo por socio a la vez — "redefinir la rutina" es desactivar este y crear uno
-- nuevo (ver WorkoutService.replacePlan), nunca se edita un plan existente in-place: los logs
-- viejos quedan intactos apuntando al plan anterior, como historia.
CREATE UNIQUE INDEX uk_workout_plan_one_active_per_member ON workout_plan (member_id) WHERE active;
CREATE INDEX idx_workout_plan_member_id ON workout_plan (member_id);

CREATE TABLE plan_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_plan_id BIGINT NOT NULL,
    order_index INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT fk_plan_day_workout_plan FOREIGN KEY (workout_plan_id) REFERENCES workout_plan (id) ON DELETE CASCADE
);

CREATE INDEX idx_plan_day_workout_plan_id ON plan_day (workout_plan_id, order_index);

-- 1 registro por reserva asistida (reservation.checked_in_at IS NOT NULL) — nunca uno suelto.
-- suggested_plan_day_id queda fijo para siempre (lo que el sistema calculó en el momento de
-- crear el log), es la base de "¿coincidió con lo sugerido o se desvió?" en la ficha del
-- profesor. plan_day_id null = el socio escribió texto libre en vez de aceptar la sugerencia.
CREATE TABLE member_workout_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    suggested_plan_day_id BIGINT NOT NULL,
    plan_day_id BIGINT,
    free_text_label VARCHAR(255),
    exercises_log JSONB,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_member_workout_log_reservation UNIQUE (reservation_id),
    CONSTRAINT fk_member_workout_log_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_workout_log_suggested_day FOREIGN KEY (suggested_plan_day_id) REFERENCES plan_day (id) ON DELETE CASCADE,
    CONSTRAINT fk_member_workout_log_plan_day FOREIGN KEY (plan_day_id) REFERENCES plan_day (id) ON DELETE CASCADE
);

CREATE INDEX idx_member_workout_log_suggested_day ON member_workout_log (suggested_plan_day_id);

ALTER TABLE workout_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE plan_day ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_workout_log ENABLE ROW LEVEL SECURITY;
