CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(180) NOT NULL,
    google_sub VARCHAR(60),
    name VARCHAR(150) NOT NULL,
    role VARCHAR(20) NOT NULL,
    gym_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT uk_app_user_google_sub UNIQUE (google_sub),
    CONSTRAINT fk_app_user_gym FOREIGN KEY (gym_id) REFERENCES gym (id) ON DELETE CASCADE
);

CREATE INDEX idx_app_user_gym_id ON app_user (gym_id);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_block_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    class_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservation_gym_block FOREIGN KEY (gym_block_id) REFERENCES gym_block (id) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_member FOREIGN KEY (member_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_reservation_slot UNIQUE (gym_block_id, member_id, class_date)
);

CREATE INDEX idx_reservation_gym_block_id ON reservation (gym_block_id);
CREATE INDEX idx_reservation_member_id ON reservation (member_id);
