-- Email + contraseña como alternativa a Google: convive con el login de Google de siempre (la
-- misma AppUser puede tener googleSub y/o passwordHash a la vez, se matchea igual por email).
-- Ver diseño en memoria de proyecto mygym_password_auth.

ALTER TABLE app_user ADD COLUMN password_hash VARCHAR(255);

-- Token de un solo uso para las 3 variantes del mismo mecanismo (ver AuthTokenPurpose):
-- INVITE (admin agregó un socio y éste activa con contraseña en vez de Google),
-- SELF_REGISTER (alta pública en /j/{slug} sin Google — app_user_id queda null hasta activar,
-- los datos del alta se guardan en las columnas pending_* mientras tanto) y
-- PASSWORD_RESET ("olvidé mi contraseña"). Solo se guarda el hash del token, nunca el valor
-- crudo (igual que una contraseña) — si se filtra la tabla, no sirve para nada por sí solo.
CREATE TABLE auth_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT,
    purpose VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    pending_name VARCHAR(255),
    pending_email VARCHAR(255),
    pending_gym_id BIGINT,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_auth_token_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_auth_token_hash ON auth_token (token_hash);

ALTER TABLE auth_token ENABLE ROW LEVEL SECURITY;
