-- Ajustes del panel de admin 2026-10-10:
-- 1) La ventana única "cancellationWindowHours" se divide en dos límites independientes, en
--    minutos (antes el mismo dato servía para reservar Y cancelar). Se poblan ambas con el valor
--    actual convertido a minutos para no cambiar el comportamiento de ningún gym existente.
--    cancellation_window_hours queda en la tabla sin uso (se borra en una migración posterior).
ALTER TABLE gym ADD COLUMN booking_window_minutes INT NOT NULL DEFAULT 120;
ALTER TABLE gym ADD COLUMN cancellation_window_minutes INT NOT NULL DEFAULT 120;
UPDATE gym SET booking_window_minutes = cancellation_window_hours * 60,
               cancellation_window_minutes = cancellation_window_hours * 60;
-- La columna vieja ya no se escribe con un valor real (Gym.cancellationWindowHours queda en 0 en
-- los gyms nuevos) y V8 le puso CHECK (> 0): sin soltar esa restricción, crear un gimnasio nuevo
-- fallaría al insertar. Se suelta acá; la columna entera se borra en una migración posterior.
ALTER TABLE gym DROP CONSTRAINT ck_gym_cancellation_window;

-- 2) Ventaja de la lista de espera, antes fija en 10 min (WaitlistService.HEAD_START_MINUTES).
--    Default 30 para TODOS los gyms (decisión explícita del usuario, no es el valor viejo).
ALTER TABLE gym ADD COLUMN waitlist_head_start_minutes INT NOT NULL DEFAULT 30;

-- 3) Privacidad: algunos gyms no quieren que los socios vean quién más va a una clase. Default
--    true = comportamiento actual (visible). La pantalla de TV nunca se ve afectada por esto.
ALTER TABLE gym ADD COLUMN show_attendees_to_members BOOLEAN NOT NULL DEFAULT true;

-- Mismos límites que valida BookingRulesRequest en la API (0 a 7 días).
ALTER TABLE gym ADD CONSTRAINT ck_gym_booking_rules CHECK (
    booking_window_minutes BETWEEN 0 AND 10080
    AND cancellation_window_minutes BETWEEN 0 AND 10080
    AND waitlist_head_start_minutes BETWEEN 0 AND 10080
);

-- 4) Registro de pagos manuales (transferencia/efectivo marcados a mano por el admin) — antes
--    GymService.simulatePlanPayment no dejaba ningún rastro del pago, solo actualizaba al socio.
--    FK en cascada: alineado con el borrado real de socios/gyms que ya existe en el resto del
--    esquema (ver mygym_gym_disconnection_feature_2026_09_23 / member delete cascade).
CREATE TABLE manual_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL REFERENCES gym (id) ON DELETE CASCADE,
    member_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    plan_id BIGINT NOT NULL REFERENCES gym_plan (id) ON DELETE CASCADE,
    amount_clp INT NOT NULL,
    bank VARCHAR(100) NOT NULL,
    registered_by_user_id BIGINT REFERENCES app_user (id) ON DELETE SET NULL,
    paid_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_manual_payment_gym_paid_at ON manual_payment (gym_id, paid_at DESC);
-- Borrar un socio cascadea a manual_payment por member_id: sin este índice cada borrado recorre la
-- tabla entera (las FK no crean índice solas en Postgres).
CREATE INDEX idx_manual_payment_member ON manual_payment (member_id);
