CREATE TABLE gym_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(280),
    category VARCHAR(30),
    price_clp INTEGER NOT NULL,
    monthly_classes INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_gym_plan_gym FOREIGN KEY (gym_id) REFERENCES gym (id) ON DELETE CASCADE,
    CONSTRAINT ck_gym_plan_price CHECK (price_clp >= 0),
    CONSTRAINT ck_gym_plan_monthly_classes CHECK (monthly_classes IS NULL OR monthly_classes > 0)
);

CREATE INDEX idx_gym_plan_gym_id ON gym_plan (gym_id);

-- monthly_classes NULL = plan libre (reserva ilimitada en cupos disponibles).
-- Ver V4__enable_row_level_security.sql: toda tabla nueva se enciende acá mismo
-- porque el backend usa JDBC directo (bypassa RLS) y solo bloquea el API REST
-- autogenerado de Supabase.
ALTER TABLE gym_plan ENABLE ROW LEVEL SECURITY;
