-- Identidad libre del gym (texto propio, redes, ventana de cancelación configurable)
ALTER TABLE gym ADD COLUMN tagline VARCHAR(160);
ALTER TABLE gym ADD COLUMN description VARCHAR(600);
ALTER TABLE gym ADD COLUMN instagram_url VARCHAR(200);
ALTER TABLE gym ADD COLUMN whatsapp_number VARCHAR(30);
ALTER TABLE gym ADD COLUMN cancellation_window_hours INTEGER NOT NULL DEFAULT 2;
ALTER TABLE gym ADD CONSTRAINT ck_gym_cancellation_window CHECK (cancellation_window_hours > 0);

-- Detalle de clase: categoría (texto libre, el frontend le asigna un ícono
-- por palabra clave) e instructor a cargo del bloque.
ALTER TABLE gym_block ADD COLUMN category VARCHAR(40);
ALTER TABLE gym_block ADD COLUMN instructor_name VARCHAR(80);
ALTER TABLE gym_block ADD COLUMN instructor_photo TEXT;

-- Galería de fotos de las instalaciones — mismo patrón que gym.logo_svg
-- (data URI base64 guardado directo en la fila, sin storage externo).
CREATE TABLE gym_photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL,
    data TEXT NOT NULL,
    caption VARCHAR(160),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_gym_photo_gym FOREIGN KEY (gym_id) REFERENCES gym (id) ON DELETE CASCADE
);

CREATE INDEX idx_gym_photo_gym_id ON gym_photo (gym_id);

ALTER TABLE gym_photo ENABLE ROW LEVEL SECURITY;
